<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>devbox_api</RootNamespace>
  </PropertyGroup>

 <ItemGroup>
 </ItemGroup>

 <ItemGroup>
   <PackageReference Include="Azure.AI.OpenAI" Version="2.5.0-beta.1" />
   <PackageReference Include="Azure.Identity" Version="1.17.0" />
   <PackageReference Include="Microsoft.Agents.AI" Version="1.0.0-preview.251104.1" />
   <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-preview.251028.1" />
   <PackageReference Include="Microsoft.Extensions.AI" Version="9.10.2" />
   <PackageReference Include="System.Text.Json" Version="10.0.0-rc.2.25502.107" />
   <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.13" />
   <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
   <PackageReference Include="YamlDotNet" Version="16.3.0" />
 </ItemGroup>
</Project>
